name: pipeline_digital_ads
version: "1.0"
config-version: 2

profile: pipeline_google_ads

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"

models:
  ads_warehouse:

    stg:
      +materialized: ephemeral

    int:
      +materialized: ephemeral

    mart:
      +materialized: table
      +tags: ["mart"]
