name: pipeline_digital_ads
version: "1.0"
config-version: 2

profile: pipeline_google_ads

# Paths
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"

vars:
  company: "{{ env_var('COMPANY') }}"
  department: "{{ env_var('DEPARTMENT') }}"
  account: "{{ env_var('ACCOUNT') }}"

models:
  pipeline_digital_ads:

    stg:
      +materialized: ephemeral

    int:
      +materialized: ephemeral

    mart:
      +materialized: table
      +tags: ["mart"]